### ISSUE TITLE
Publish to bower

### ISSUE THREAD

**Issue by NickSeagull** [fluffynukeit/purescript-foreign-callbacks#3]
I think this library is very useful for a lot of people and it would be awesome if it was published on Bower for ease of installation. 😁

**Comment by fluffynukeit** [comment]
You're welcome to take it over!  I haven't played with any purescript in probably over a year, and I don't have any plans to.  Help yourself. :)  Glad someone finds it useful.

**Comment by NickSeagull** [comment]
Just opened a PR ( #4  ) 😁 Closing this
